apiVersion: v1
kind: Service
metadata:
  name: login-page-service
spec:
  selector:
    app: login-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer


  #kubectl port-forward service/your-app-service 9090:80
  #access the page at http://localhost:9090/login-page/
